# Versão do arquivo docker-compose.yml
version: '3.9'

# Serviços (containers)
services:

    # Base de dados (PostgreSQL)
    postgres:
        image: guilhermebigois/postgres4protheus
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            PROTHEUS_DBUSER: qa
            PROTHEUS_DBPASSWORD: eg6i8e6z
            PROTHEUS_DBNAME: homolog
        ports:
            - 5432:5432

            