-- Criação do usuário Protheus
CREATE USER {{PROTHEUS_DBUSER}}
WITH
	PASSWORD '{{PROTHEUS_DBPASSWORD}}';

-- Criação do banco Protheus
CREATE DATABASE {{PROTHEUS_DBNAME}}
WITH
	OWNER = {{PROTHEUS_DBUSER}}
	ENCODING = 'WIN1252'
	LC_COLLATE = 'C'
	LC_CTYPE = 'C'
	CONNECTION LIMIT = -1
	TEMPLATE template0;
